name: Setup ChromeDriver

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  setup-chromedriver:
    runs-on: ubuntu-latest
    steps:
    - name: Check Chrome version and install ChromeDriver
      run: |
        set -e

        CHROME_VERSION_FULL=$(google-chrome --version | grep -oP '\d+\.\d+(\.\d+)*')
        echo "Chrome full version: $CHROME_VERSION_FULL"

        CHROME_MAJOR_MINOR=$(echo $CHROME_VERSION_FULL | cut -d. -f1,2)
        echo "Chrome major.minor version: $CHROME_MAJOR_MINOR"

        CHROMEDRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_MINOR}")

        if [[ -z "$CHROMEDRIVER_VERSION" ]] || [[ "$CHROMEDRIVER_VERSION" == *"<Error>"* ]]; then
          echo "没有官方版本，使用备用版本 137.0.7151.68"
          CHROMEDRIVER_VERSION="137.0.7151.68"
        fi

        echo "ChromeDriver version: $CHROMEDRIVER_VERSION"

        wget -N "https://github.com/dreamshao/chromedriver/releases/download/${CHROMEDRIVER_VERSION}/chromedriver-linux64.zip"
        unzip -o chromedriver-linux64.zip
        sudo mv -f chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

        chromedriver --version
